apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-deployment
  labels:
    app: medicure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medicure
  template:
    metadata:
      labels:
        app: medicure
    spec:
      containers:
      - name: medicure-container
        image: subbuvenu/medicure-project:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: medicure-nodeport-svc
  labels:
    app: medicure
spec:
  selector:
    app: medicure
  type: NodePort
  ports:
  - nodePort: 31035   # choose an unused NodePort
    port: 8080
    targetPort: 8080
